version: '3.9'

# Run production docker image locally

services:
  app:
    environment:
      - PORT
      - HOST
      - SECRET_KEY
      - ALLOWED_HOSTS=localhost,0.0.0.0,127.0.0.1
      - CSRF_TRUSTED_ORIGINS=http://localhost,http://0.0.0.0,http://127.0.0.1
    image: '${DOCKER_IMAGE_REPO}:latest'
